# Generated by Django 3.2.3 on 2021-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumedmeals',
            name='calories',
            field=models.IntegerField(default=323),
        ),
    ]
