# Generated by Django 3.2.3 on 2021-06-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_consumedmeals_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumedmeals',
            name='mealType',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='consumedmeals',
            name='date',
            field=models.DateField(blank=True, default=8),
        ),
    ]
