# Generated by Django 3.2.3 on 2021-07-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210627_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lattitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='meal',
            field=models.ManyToManyField(to='API.Recipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mealPlans',
            field=models.ManyToManyField(related_name='user', to='API.mealPlan'),
        ),
        migrations.CreateModel(
            name='menuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.restaurant')),
            ],
        ),
    ]
