# Generated by Django 3.2.3 on 2021-06-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210608_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumedmeals',
            name='date',
        ),
    ]
