# Generated by Django 3.2.3 on 2021-06-08 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_consumedmeals_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumedmeals',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2021, 6, 8)),
            preserve_default=False,
        ),
    ]
