# Generated by Django 3.2.3 on 2021-07-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210708_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
