# Generated by Django 3.2.3 on 2021-07-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_lattitude_restaurant_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuItem', to='API.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=11),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=11),
        ),
    ]
