# Generated by Django 3.2.3 on 2021-07-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumedmeals',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consumedmeals',
            name='meal',
            field=models.CharField(max_length=100),
        ),
    ]
